'use client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Privacy() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-grow pt-24 pb-16 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
          <div className="prose prose-blue max-w-none">
            <p className="text-sm text-gray-500 mb-8">Last Updated: March 22, 2025</p>
            
            <p className="text-gray-700 leading-relaxed mb-6">
              Thank you for visiting Image Prompt ("we," "us," or "our"). This Privacy Policy outlines how we collect, use, and protect your personal and non-personal information when you use our website located at https://imageprompt.vip (the "Website").
            </p>
            
            <p className="text-gray-700 leading-relaxed mb-8">
              By accessing or using the Website, you agree to the terms of this Privacy Policy. If you do not agree with the practices described in this policy, please do not use the Website.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Information We Collect</h2>
            
            <h3 className="text-xl font-medium mt-6 mb-3">1.1 Personal Data</h3>
            <p className="text-gray-700 mb-4">We collect the following personal information from you:</p>
            <ul className="list-disc pl-6 mb-6 text-gray-700">
              <li className="mb-2">Name: We collect your name to personalize your experience and communicate with you effectively.</li>
              <li className="mb-2">Email: We collect your email address to send you important information regarding your orders, updates, and communication.</li>
              <li className="mb-2">Payment Information: We collect payment details to process your orders securely. However, we do not store your payment information on our servers. Payments are processed by trusted third-party payment processors.</li>
            </ul>

            <h3 className="text-xl font-medium mt-6 mb-3">1.2 Non-Personal Data</h3>
            <p className="text-gray-700 mb-6">
              We may use web cookies and similar technologies to collect non-personal information such as your IP address, browser type, device information, and browsing patterns. This information helps us to enhance our browsing experience, analyze trends, and improve our services.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">1.3 Cookies and Tracking Technologies</h3>
            <p className="text-gray-700 mb-4">We use cookies and similar tracking technologies to enhance your experience on our Website:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700">
              <li className="mb-2">Session Cookies: These are temporary cookies that expire when you close your browser. We use them to maintain your session and authentication state.</li>
              <li className="mb-2">Persistent Cookies: These cookies remain on your device until they expire or you delete them. They help us remember your preferences and login information.</li>
            </ul>

            <p className="text-gray-700 mb-4">Our cookies are used for:</p>
            <ul className="list-disc pl-6 mb-6 text-gray-700">
              <li>Authentication and security</li>
              <li>Maintaining your login session</li>
              <li>Remembering your preferences</li>
              <li>Analyzing website usage to improve our services</li>
            </ul>

            <p className="text-gray-700 mb-6">
              You can control cookie settings through your browser preferences. However, disabling certain cookies may limit your ability to use some features of our Website.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Analytics and Third-Party Services</h2>
            <p className="text-gray-700 mb-4">
              We use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help us analyze how users use our Website. The information generated by these cookies about your use of the Website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
            </p>

            <p className="text-gray-700 mb-4">Google will use this information for the purpose of:</p>
            <ul className="list-disc pl-6 mb-6 text-gray-700">
              <li>Evaluating your use of the Website</li>
              <li>Compiling reports on website activity</li>
              <li>Providing other services relating to website activity and internet usage</li>
            </ul>

            <p className="text-gray-700 mb-6">
              You can prevent Google Analytics from recognizing you on return visits to this Website by disabling cookies in your browser or by using Google Analytics' opt-out browser add-on, available at: https://tools.google.com/dlpage/gaoptout
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">2. Purpose of Data Collection</h2>
            <p className="text-gray-700 mb-6">
              We collect and use your personal data for the sole purpose of order processing. This includes processing your orders, sending order confirmations, providing customer support, and keeping you updated about the status of your orders.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">3. Data Sharing</h2>
            <p className="text-gray-700 mb-6">
              We do not share your personal data with any third parties except as required for order processing (e.g., sharing your information with payment processors). We do not sell, trade, or rent your personal information to others.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">4. Children's Privacy</h2>
            <p className="text-gray-700 mb-6">
              Image Prompt is not intended for children under the age of 13. We do not knowingly collect personal information from children. If you are a parent or guardian and believe that your child has provided us with personal information, please contact us at the email address provided below.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">5. Updates to the Privacy Policy</h2>
            <p className="text-gray-700 mb-6">
              We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. Any updates will be posted on this page, and we may notify you via email about significant changes.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">6. Contact Information</h2>
            <p className="text-gray-700 mb-4">
              If you have any questions, concerns, or requests related to this Privacy Policy, you can contact us at.
            </p>
            <p className="text-gray-700 mb-6">
              For all other inquiries, please visit our Contact Us page on the Website.
            </p>
            <p className="text-gray-700 mt-8 font-medium">
              By using Image Prompt, you consent to the terms of this Privacy Policy.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
